# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('chicago', '0002_chicagoevent_torontoperson'), ('chicago', '0003_auto_20160623_1843'), ('chicago', '0004_auto_20160628_1556'), ('chicago', '0005_torontoorganization')]

    dependencies = [
        ('councilmatic_core', '0010_auto_20160120_1248'),
        ('chicago', '0001_initial'),
        ('councilmatic_core', '0011_bill_extras'),
        ('councilmatic_core', '0012_auto_20160707_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicagoEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.event',),
        ),
        migrations.CreateModel(
            name='TorontoPerson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.person',),
        ),
        migrations.DeleteModel(
            name='ChicagoBill',
        ),
        migrations.CreateModel(
            name='ChicagoBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='TorontoOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.organization',),
        ),
    ]
