# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('toronto', '0001_initial'), ('toronto', '0002_chicagoevent_torontoperson_squashed_0005_torontoorganization'), ('toronto', '0003_auto_20160708_2353')]

    initial = True

    dependencies = [
        ('councilmatic_core', '0001_initial'),
        ('councilmatic_core', '0011_bill_extras'),
        ('councilmatic_core', '0012_auto_20160707_1859'),
        ('councilmatic_core', '0010_auto_20160120_1248'),
        ('councilmatic_core', '0013_auto_20160707_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicagoBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='ChicagoEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.event',),
        ),
        migrations.CreateModel(
            name='TorontoPerson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.person',),
        ),
        migrations.DeleteModel(
            name='ChicagoBill',
        ),
        migrations.CreateModel(
            name='ChicagoBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='TorontoOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.organization',),
        ),
        migrations.DeleteModel(
            name='ChicagoBill',
        ),
        migrations.DeleteModel(
            name='ChicagoEvent',
        ),
        migrations.CreateModel(
            name='TorontoBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='TorontoEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.event',),
        ),
    ]
