# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0013_auto_20160707_1957'),
        ('chicago', '0002_chicagoevent_torontoperson_squashed_0005_torontoorganization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChicagoBill',
        ),
        migrations.DeleteModel(
            name='ChicagoEvent',
        ),
        migrations.CreateModel(
            name='TorontoBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='TorontoEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.event',),
        ),
    ]
