# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0012_auto_20160707_1859'),
        ('chicago', '0004_auto_20160628_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorontoOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.organization',),
        ),
    ]
